// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh-CN'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	meta: {
		/**
		 * e​n
		 */
		lang: string
		/**
		 * M​F​u​s​e​ ​—​ ​R​e​m​o​t​e​ ​f​i​l​e​s​y​s​t​e​m​s​,​ ​n​a​t​i​v​e​ ​m​a​c​O​S​ ​s​p​e​e​d
		 */
		title: string
		/**
		 * M​F​u​s​e​ ​—​ ​M​o​u​n​t​ ​r​e​m​o​t​e​ ​f​i​l​e​s​y​s​t​e​m​s​ ​a​t​ ​n​a​t​i​v​e​ ​m​a​c​O​S​ ​s​p​e​e​d​.​ ​S​F​T​P​,​ ​S​3​,​ ​W​e​b​D​A​V​,​ ​S​M​B​,​ ​F​T​P​,​ ​N​F​S​,​ ​a​n​d​ ​G​o​o​g​l​e​ ​D​r​i​v​e​ ​i​n​ ​o​n​e​ ​F​i​n​d​e​r​-​n​a​t​i​v​e​ ​w​o​r​k​f​l​o​w​.
		 */
		description: string
	}
	nav: {
		/**
		 * F​e​a​t​u​r​e​s
		 */
		features: string
		/**
		 * P​r​o​t​o​c​o​l​s
		 */
		protocols: string
		/**
		 * T​e​s​t​i​m​o​n​i​a​l​s
		 */
		testimonials: string
		/**
		 * D​o​w​n​l​o​a​d
		 */
		download: string
		/**
		 * L​a​n​g​u​a​g​e
		 */
		languageLabel: string
	}
	hero: {
		/**
		 * R​e​m​o​t​e​ ​f​i​l​e​s​y​s​t​e​m​s​,
		 */
		titlePrefix: string
		/**
		 * n​a​t​i​v​e​ ​m​a​c​O​S​ ​s​p​e​e​d​.
		 */
		titleSuffix: string
		/**
		 * M​F​u​s​e​ ​u​n​i​f​i​e​s​ ​d​i​s​t​r​i​b​u​t​e​d​ ​s​t​o​r​a​g​e​ ​i​n​t​o​ ​o​n​e​ ​F​i​n​d​e​r​-​n​a​t​i​v​e​ ​w​o​r​k​f​l​o​w​ ​—​ ​S​F​T​P​,​ ​S​3​,​ ​W​e​b​D​A​V​,​ ​S​M​B​,​ ​F​T​P​,​ ​N​F​S​,​ ​a​n​d​ ​G​o​o​g​l​e​ ​D​r​i​v​e​,​ ​a​l​l​ ​m​o​u​n​t​e​d​ ​t​r​a​n​s​p​a​r​e​n​t​l​y​.
		 */
		subtitle: string
		/**
		 * D​o​w​n​l​o​a​d​ ​f​o​r​ ​m​a​c​O​S
		 */
		primaryAction: string
		/**
		 * S​e​e​ ​h​o​w​ ​i​t​ ​w​o​r​k​s
		 */
		secondaryAction: string
	}
	features: {
		/**
		 * O​n​e​ ​m​o​u​n​t​ ​l​a​y​e​r​.​ ​E​v​e​r​y​ ​p​r​o​t​o​c​o​l​ ​y​o​u​r​ ​t​e​a​m​ ​d​e​p​e​n​d​s​ ​o​n​.
		 */
		title: string
		/**
		 * A​ ​d​e​n​s​e​ ​c​a​p​a​b​i​l​i​t​y​ ​s​u​r​f​a​c​e​ ​w​i​t​h​ ​n​o​ ​d​e​c​o​r​a​t​i​v​e​ ​f​i​l​l​e​r​ ​—​ ​e​v​e​r​y​ ​b​l​o​c​k​ ​m​a​p​s​ ​t​o​ ​a​ ​r​e​a​l​ ​o​p​e​r​a​t​i​o​n​a​l​ ​o​u​t​c​o​m​e​.
		 */
		subtitle: string
		nativeFinder: {
			/**
			 * N​a​t​i​v​e​ ​F​i​n​d​e​r​ ​I​n​t​e​g​r​a​t​i​o​n
			 */
			title: string
			/**
			 * U​s​e​s​ ​t​h​e​ ​m​a​c​O​S​ ​F​i​l​e​ ​P​r​o​v​i​d​e​r​ ​A​P​I​ ​s​o​ ​r​e​m​o​t​e​ ​v​o​l​u​m​e​s​ ​a​p​p​e​a​r​,​ ​b​r​o​w​s​e​,​ ​a​n​d​ ​b​e​h​a​v​e​ ​e​x​a​c​t​l​y​ ​l​i​k​e​ ​l​o​c​a​l​ ​f​o​l​d​e​r​s​.
			 */
			description: string
		}
		workspace: {
			/**
			 * C​r​o​s​s​-​P​r​o​t​o​c​o​l​ ​W​o​r​k​s​p​a​c​e
			 */
			title: string
			/**
			 * M​o​u​n​t​ ​S​F​T​P​,​ ​S​3​,​ ​W​e​b​D​A​V​,​ ​S​M​B​,​ ​F​T​P​,​ ​N​F​S​,​ ​a​n​d​ ​G​o​o​g​l​e​ ​D​r​i​v​e​ ​s​i​d​e​ ​b​y​ ​s​i​d​e​ ​i​n​ ​a​ ​s​i​n​g​l​e​ ​F​i​n​d​e​r​-​n​a​t​i​v​e​ ​s​u​r​f​a​c​e​.
			 */
			description: string
		}
		credentials: {
			/**
			 * C​r​e​d​e​n​t​i​a​l​ ​I​s​o​l​a​t​i​o​n
			 */
			title: string
			/**
			 * P​r​o​t​o​c​o​l​-​s​p​e​c​i​f​i​c​ ​c​r​e​d​e​n​t​i​a​l​ ​h​a​n​d​l​i​n​g​ ​r​e​d​u​c​e​s​ ​c​r​o​s​s​-​s​y​s​t​e​m​ ​l​e​a​k​a​g​e​ ​r​i​s​k​ ​i​n​ ​m​i​x​e​d​ ​e​n​v​i​r​o​n​m​e​n​t​s​.
			 */
			description: string
		}
		metadata: {
			/**
			 * T​r​a​n​s​p​a​r​e​n​t​ ​M​e​t​a​d​a​t​a
			 */
			title: string
			/**
			 * F​i​l​e​ ​s​i​z​e​,​ ​o​w​n​e​r​s​h​i​p​,​ ​a​n​d​ ​m​o​d​i​f​i​e​d​ ​t​i​m​e​s​t​a​m​p​s​ ​a​r​e​ ​v​i​s​i​b​l​e​ ​b​e​f​o​r​e​ ​t​r​a​n​s​f​e​r​,​ ​r​i​g​h​t​ ​i​n​s​i​d​e​ ​F​i​n​d​e​r​.
			 */
			description: string
		}
		reconnect: {
			/**
			 * R​e​l​i​a​b​l​e​ ​R​e​c​o​n​n​e​c​t
			 */
			title: string
			/**
			 * P​r​e​d​i​c​t​a​b​l​e​ ​m​o​u​n​t​ ​l​i​f​e​c​y​c​l​e​ ​a​c​r​o​s​s​ ​l​o​n​g​-​r​u​n​n​i​n​g​ ​d​e​s​k​t​o​p​ ​s​e​s​s​i​o​n​s​ ​a​n​d​ ​u​n​s​t​a​b​l​e​ ​n​e​t​w​o​r​k​ ​w​i​n​d​o​w​s​.
			 */
			description: string
		}
	}
	protocols: {
		/**
		 * A​l​l​ ​t​h​e​ ​p​r​o​t​o​c​o​l​s​.​ ​O​n​e​ ​n​a​t​i​v​e​ ​e​x​p​e​r​i​e​n​c​e​.
		 */
		title: string
		/**
		 * E​a​c​h​ ​b​a​c​k​e​n​d​ ​i​s​ ​a​ ​s​e​l​f​-​c​o​n​t​a​i​n​e​d​ ​S​w​i​f​t​ ​p​a​c​k​a​g​e​ ​i​m​p​l​e​m​e​n​t​i​n​g​ ​t​h​e​ ​s​h​a​r​e​d​ ​R​e​m​o​t​e​F​i​l​e​S​y​s​t​e​m​ ​i​n​t​e​r​f​a​c​e​,​ ​k​e​e​p​i​n​g​ ​p​r​o​t​o​c​o​l​ ​s​p​e​c​i​f​i​c​s​ ​i​s​o​l​a​t​e​d​ ​f​r​o​m​ ​t​h​e​ ​a​p​p​ ​a​n​d​ ​t​h​e​ ​F​i​l​e​ ​P​r​o​v​i​d​e​r​ ​e​x​t​e​n​s​i​o​n​.
		 */
		subtitle: string
		/**
		 * #​ ​t​a​p​ ​t​h​e​ ​c​u​s​t​o​m​ ​r​e​p​o
		 */
		installTapPrompt: string
		/**
		 * #​ ​i​n​s​t​a​l​l​ ​M​F​u​s​e
		 */
		installCaskPrompt: string
	}
	testimonials: {
		/**
		 * T​r​u​s​t​e​d​ ​b​y​ ​t​e​a​m​s​ ​t​h​a​t​ ​m​o​v​e​ ​f​a​s​t​.
		 */
		title: string
		papercube: {
			/**
			 * M​F​u​s​e​ ​r​e​p​l​a​c​e​d​ ​t​h​r​e​e​ ​m​o​u​n​t​i​n​g​ ​t​o​o​l​s​ ​i​n​ ​o​u​r​ ​s​t​a​c​k​ ​w​h​i​l​e​ ​k​e​e​p​i​n​g​ ​F​i​n​d​e​r​ ​b​e​h​a​v​i​o​r​ ​i​n​s​t​a​n​t​l​y​ ​f​a​m​i​l​i​a​r​ ​t​o​ ​e​v​e​r​y​ ​t​e​a​m​.
			 */
			quote: string
			/**
			 * i​O​S​ ​D​e​v​e​l​o​p​e​r
			 */
			role: string
		}
		wyy: {
			/**
			 * O​n​b​o​a​r​d​i​n​g​ ​r​e​m​o​t​e​ ​s​t​o​r​a​g​e​ ​w​o​r​k​f​l​o​w​s​ ​n​o​w​ ​t​a​k​e​s​ ​h​o​u​r​s​,​ ​n​o​t​ ​w​e​e​k​s​.​ ​T​h​e​ ​b​a​c​k​e​n​d​ ​a​b​s​t​r​a​c​t​i​o​n​ ​i​s​ ​g​e​n​u​i​n​e​l​y​ ​c​l​e​a​n​.
			 */
			quote: string
			/**
			 * I​n​f​r​a​s​t​r​u​c​t​u​r​e​ ​L​e​a​d
			 */
			role: string
		}
		eurafat45: {
			/**
			 * T​e​a​m​s​ ​m​o​v​e​ ​c​o​n​t​e​n​t​ ​b​e​t​w​e​e​n​ ​S​3​ ​a​n​d​ ​S​M​B​ ​w​i​t​h​ ​f​e​w​e​r​ ​h​a​n​d​o​f​f​ ​e​r​r​o​r​s​ ​a​n​d​ ​t​i​g​h​t​e​r​ ​o​p​e​r​a​t​i​o​n​a​l​ ​v​i​s​i​b​i​l​i​t​y​.
			 */
			quote: string
			/**
			 * S​t​u​d​e​n​t
			 */
			role: string
		}
	}
	cta: {
		/**
		 * M​F​u​s​e​ ​i​s​ ​f​r​e​e​ ​a​n​d​ ​o​p​e​n​ ​s​o​u​r​c​e​ ​u​n​d​e​r​ ​A​G​P​L​v​3​.
		 */
		title: string
		/**
		 * I​n​s​t​a​l​l​ ​f​r​o​m​ ​t​h​e​ ​H​o​m​e​b​r​e​w​ ​t​a​p​ ​o​r​ ​d​o​w​n​l​o​a​d​ ​a​ ​p​a​c​k​a​g​e​d​ ​b​u​i​l​d​ ​f​r​o​m​ ​G​i​t​H​u​b​ ​R​e​l​e​a​s​e​s​.​ ​F​r​e​e​ ​s​o​f​t​w​a​r​e​,​ ​n​o​ ​p​a​i​d​ ​l​o​c​k​-​i​n​.
		 */
		subtitle: string
		/**
		 * I​n​s​t​a​l​l​ ​f​r​o​m​ ​H​o​m​e​b​r​e​w​ ​T​a​p
		 */
		homebrewAction: string
		/**
		 * D​o​w​n​l​o​a​d​ ​f​r​o​m​ ​G​i​t​H​u​b​ ​R​e​l​e​a​s​e​s
		 */
		githubAction: string
	}
	footer: {
		/**
		 * F​e​a​t​u​r​e​s
		 */
		features: string
		/**
		 * P​r​o​t​o​c​o​l​s
		 */
		protocols: string
		/**
		 * R​e​l​e​a​s​e​s
		 */
		releases: string
	}
}

export type TranslationFunctions = {
	meta: {
		/**
		 * en
		 */
		lang: () => LocalizedString
		/**
		 * MFuse — Remote filesystems, native macOS speed
		 */
		title: () => LocalizedString
		/**
		 * MFuse — Mount remote filesystems at native macOS speed. SFTP, S3, WebDAV, SMB, FTP, NFS, and Google Drive in one Finder-native workflow.
		 */
		description: () => LocalizedString
	}
	nav: {
		/**
		 * Features
		 */
		features: () => LocalizedString
		/**
		 * Protocols
		 */
		protocols: () => LocalizedString
		/**
		 * Testimonials
		 */
		testimonials: () => LocalizedString
		/**
		 * Download
		 */
		download: () => LocalizedString
		/**
		 * Language
		 */
		languageLabel: () => LocalizedString
	}
	hero: {
		/**
		 * Remote filesystems,
		 */
		titlePrefix: () => LocalizedString
		/**
		 * native macOS speed.
		 */
		titleSuffix: () => LocalizedString
		/**
		 * MFuse unifies distributed storage into one Finder-native workflow — SFTP, S3, WebDAV, SMB, FTP, NFS, and Google Drive, all mounted transparently.
		 */
		subtitle: () => LocalizedString
		/**
		 * Download for macOS
		 */
		primaryAction: () => LocalizedString
		/**
		 * See how it works
		 */
		secondaryAction: () => LocalizedString
	}
	features: {
		/**
		 * One mount layer. Every protocol your team depends on.
		 */
		title: () => LocalizedString
		/**
		 * A dense capability surface with no decorative filler — every block maps to a real operational outcome.
		 */
		subtitle: () => LocalizedString
		nativeFinder: {
			/**
			 * Native Finder Integration
			 */
			title: () => LocalizedString
			/**
			 * Uses the macOS File Provider API so remote volumes appear, browse, and behave exactly like local folders.
			 */
			description: () => LocalizedString
		}
		workspace: {
			/**
			 * Cross-Protocol Workspace
			 */
			title: () => LocalizedString
			/**
			 * Mount SFTP, S3, WebDAV, SMB, FTP, NFS, and Google Drive side by side in a single Finder-native surface.
			 */
			description: () => LocalizedString
		}
		credentials: {
			/**
			 * Credential Isolation
			 */
			title: () => LocalizedString
			/**
			 * Protocol-specific credential handling reduces cross-system leakage risk in mixed environments.
			 */
			description: () => LocalizedString
		}
		metadata: {
			/**
			 * Transparent Metadata
			 */
			title: () => LocalizedString
			/**
			 * File size, ownership, and modified timestamps are visible before transfer, right inside Finder.
			 */
			description: () => LocalizedString
		}
		reconnect: {
			/**
			 * Reliable Reconnect
			 */
			title: () => LocalizedString
			/**
			 * Predictable mount lifecycle across long-running desktop sessions and unstable network windows.
			 */
			description: () => LocalizedString
		}
	}
	protocols: {
		/**
		 * All the protocols. One native experience.
		 */
		title: () => LocalizedString
		/**
		 * Each backend is a self-contained Swift package implementing the shared RemoteFileSystem interface, keeping protocol specifics isolated from the app and the File Provider extension.
		 */
		subtitle: () => LocalizedString
		/**
		 * # tap the custom repo
		 */
		installTapPrompt: () => LocalizedString
		/**
		 * # install MFuse
		 */
		installCaskPrompt: () => LocalizedString
	}
	testimonials: {
		/**
		 * Trusted by teams that move fast.
		 */
		title: () => LocalizedString
		papercube: {
			/**
			 * MFuse replaced three mounting tools in our stack while keeping Finder behavior instantly familiar to every team.
			 */
			quote: () => LocalizedString
			/**
			 * iOS Developer
			 */
			role: () => LocalizedString
		}
		wyy: {
			/**
			 * Onboarding remote storage workflows now takes hours, not weeks. The backend abstraction is genuinely clean.
			 */
			quote: () => LocalizedString
			/**
			 * Infrastructure Lead
			 */
			role: () => LocalizedString
		}
		eurafat45: {
			/**
			 * Teams move content between S3 and SMB with fewer handoff errors and tighter operational visibility.
			 */
			quote: () => LocalizedString
			/**
			 * Student
			 */
			role: () => LocalizedString
		}
	}
	cta: {
		/**
		 * MFuse is free and open source under AGPLv3.
		 */
		title: () => LocalizedString
		/**
		 * Install from the Homebrew tap or download a packaged build from GitHub Releases. Free software, no paid lock-in.
		 */
		subtitle: () => LocalizedString
		/**
		 * Install from Homebrew Tap
		 */
		homebrewAction: () => LocalizedString
		/**
		 * Download from GitHub Releases
		 */
		githubAction: () => LocalizedString
	}
	footer: {
		/**
		 * Features
		 */
		features: () => LocalizedString
		/**
		 * Protocols
		 */
		protocols: () => LocalizedString
		/**
		 * Releases
		 */
		releases: () => LocalizedString
	}
}

export type Formatters = {}
